// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a scope's active provider points. Derived from the scope's `env`, not
 * stored (ADR-0001): a known profile, an env set outside the app, or none.
 */
export type ActiveProvider = { "state": "profile", id: string, } | { "state": "unmanaged" } | { "state": "subscription" };
