// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of checking whether the user has a Claude subscription OAuth session
 * in `~/.claude/.credentials.json`. `logged_in` is true when the file contains
 * a stored access or refresh token; `expires_at` is kept for display only,
 * because Claude Code refreshes access tokens automatically.
 */
export type AuthStatus = { logged_in: boolean, subscription_type: string | null, rate_limit_tier: string | null, 
/**
 * Unix timestamp in milliseconds when the access token expires, if known.
 */
expires_at: number | null, };
