// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A plugin offered by a marketplace (from the catalog cache). The description /
 * version / author are best-effort — empty when the catalog entry omits them.
 */
export type AvailablePlugin = { id: string, name: string, marketplace: string, installed: boolean, description: string, version: string, author: string, };
