// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BundledKind } from "./BundledKind";

/**
 * A resource shipped inside a plugin (shown read-only under its row, never in
 * the top-level resource tabs — ADR-0001).
 */
export type BundledResource = { kind: BundledKind, name: string, path: string, };
