// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialStatus } from "./CredentialStatus";
import type { ExtraUsage } from "./ExtraUsage";
import type { RateLimitTier } from "./RateLimitTier";

/**
 * Result of querying the Anthropic OAuth subscription quota endpoint.
 */
export type ClaudeSubscriptionQuota = { 
/**
 * Whether the credentials file contains any OAuth token at all.
 */
logged_in: boolean, 
/**
 * Status of the credentials / API request.
 */
credential_status: CredentialStatus, 
/**
 * Per-window utilization, ordered by the caller.
 */
tiers: Array<RateLimitTier>, extra_usage: ExtraUsage | null, error: string | null, };
