// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the locally stored Claude OAuth credentials.
 */
export type CredentialStatus = "valid" | "expired" | "not_found" | "parse_error";
