// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional "extra usage" / overage information.
 */
export type ExtraUsage = { is_enabled: boolean, monthly_limit: number | null, used_credits: number | null, utilization: number | null, currency: string | null, };
