// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One listed resource. `path` points at the markdown file to open/edit (a
 * skill's `SKILL.md`, or the resource file itself for flat resources).
 */
export type FileResource = { name: string, description: string | null, path: string, };
