// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookSource } from "./HookSource";

/**
 * One flattened hook: a command bound to an event (optionally gated by a
 * matcher), tagged with its source and the file it lives in (for "open file").
 */
export type HookEntry = { event: string, matcher: string | null, command: string, source: HookSource, 
/**
 * The file this hook was read from (a settings file or a plugin's
 * `hooks.json`), used by the "open file" action.
 */
source_path: string | null, };
