// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a hook came from. `user`/`plugin` show under the User panel;
 * `project`/`local` under the Project panel.
 */
export type HookSource = "user" | "project" | "local" | "plugin";
