// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An installed plugin (from `installed_plugins.json` + `settings#enabledPlugins`).
 */
export type InstalledPlugin = { 
/**
 * Full identifier, `name@marketplace`.
 */
id: string, name: string, marketplace: string, enabled: boolean, version: string, install_path: string, scope: string, };
