// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configured marketplace (from `known_marketplaces.json`).
 */
export type Marketplace = { name: string, source: string, install_location: string, };
