// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection health of an MCP server, from `claude mcp list`.
 */
export type McpHealth = { name: string, 
/**
 * `connected` / `needs_auth` / `failed` / `pending` / `unknown`.
 */
status: string, };
