// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A key/value pair on an MCP server (an env var or an HTTP header).
 */
export type McpKeyVal = { key: string, value: string, };
