// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the three MCP locations a server came from.
 */
export type McpSource = "user" | "project" | "local";
