// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpKeyVal } from "./McpKeyVal";
import type { McpSource } from "./McpSource";

/**
 * One configured MCP server.
 */
export type McpServer = { name: string, 
/**
 * `stdio` / `sse` / `http` / `unknown` — from `type`/`transport`, or
 * inferred from whether a command or url is present.
 */
transport: string, url: string | null, command: string | null, 
/**
 * stdio subprocess arguments (after the command).
 */
args: Array<string>, 
/**
 * stdio environment variables. Values may be secret — mask them in the UI.
 */
env: Array<McpKeyVal>, 
/**
 * http/sse request headers. Values may be secret — mask them in the UI.
 */
headers: Array<McpKeyVal>, source: McpSource, 
/**
 * Trust state of a **project** (`.mcp.json`) server: `approved` / `pending`
 * / `rejected`, derived from the project's enabled/disabled lists in
 * `~/.claude.json`. `None` for user/local servers, which are always active.
 */
approval: string | null, };
