// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The resolved memory directory, with enough context for a dual-path display.
 */
export type MemoryInfo = { 
/**
 * The directory memory is actually read from / written to.
 */
effective: string, 
/**
 * The default `~/.claude/projects/<slug>/memory` location.
 */
default: string, 
/**
 * True when an `autoMemoryDirectory` override is in effect.
 */
overridden: boolean, };
