// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "./AuthMode";
import type { ProviderKind } from "./ProviderKind";

/**
 * A stored profile. The secret itself never lives here — only a flag saying
 * whether one is present in the keychain.
 */
export type Profile = { id: string, name: string, kind: ProviderKind, authMode: AuthMode | null, baseUrl: string | null, 
/**
 * Whether a secret for this profile exists in the keychain.
 */
hasSecret: boolean, };
