// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "./AuthMode";
import type { ProviderKind } from "./ProviderKind";

/**
 * The fields a caller supplies to create/update a profile (no id, no
 * has_secret — those are managed by the app).
 */
export type ProfileInput = { name: string, kind: ProviderKind, authMode: AuthMode | null, baseUrl: string | null, };
