// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rate-limit window returned by Anthropic's OAuth usage endpoint.
 */
export type RateLimitTier = { 
/**
 * Window identifier, e.g. `five_hour`, `seven_day`, `seven_day_opus`.
 */
window: string, 
/**
 * Utilization ratio in the range 0.0–1.0.
 */
utilization: number, 
/**
 * Unix timestamp in seconds when the window resets, if known.
 */
resets_at: number | null, };
