// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the app learned about a project: tracked by Claude Code, added manually
 * by the user, or both.
 */
export type ScopeSource = "claude" | "manual" | "both";
