// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeKind } from "./ScopeKind";

/**
 * A sidebar entry the user can select. In slice 1 only the User scope exists;
 * project enumeration arrives in slice 2.
 */
export type Scope = { 
/**
 * Stable identity: `"user"` for the user scope, or the project's id.
 */
id: string, kind: ScopeKind, 
/**
 * Human-readable label shown in the sidebar.
 */
label: string, };
