// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a scope is the user's global config or a single project.
 */
export type ScopeKind = "user" | "project";
