// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to a scope, used as a command argument.
 *
 * `User` is the global `~/.claude/` scope; `Project` carries the project id
 * (see [`Scope::id`]).
 */
export type ScopeRef = { "kind": "user" } | { "kind": "project", id: string, };
