// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeKind } from "./ScopeKind";
import type { ScopeSource } from "./ScopeSource";

/**
 * A sidebar entry the user can select: the User scope, or one project
 * (identified canonically by its git repository root).
 */
export type Scope = { 
/**
 * Stable identity: `"user"` for the user scope, or the project's canonical
 * root path.
 */
id: string, kind: ScopeKind, 
/**
 * Human-readable label shown in the sidebar.
 */
label: string, 
/**
 * Absolute path of the project's git root; `None` for the User scope.
 */
path: string | null, 
/**
 * The project's path no longer exists on disk.
 */
stale: boolean, 
/**
 * How the project was discovered; `None` for the User scope. Only
 * manually-added projects (`Manual` / `Both`) are user-removable.
 */
source: ScopeSource | null, };
