// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session shown in the list. `id` is the transcript filename stem (the
 * session id Claude Code resumes by).
 */
export type Session = { id: string, 
/**
 * Last-modified time, epoch milliseconds.
 */
modified_ms: number, 
/**
 * First user prompt, truncated — `None` if not found.
 */
preview: string | null, };
