// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceSkill } from "./SourceSkill";

/**
 * A tracked Git repository that ships skills.
 */
export type SkillSource = { 
/**
 * Canonical nested directory name derived from the normalized URL,
 * e.g. `github.com/owner/repo`.
 */
name: string, 
/**
 * Original URL as entered by the user.
 */
url: string, 
/**
 * Skills discovered in this source.
 */
skills: Array<SourceSkill>, };
