// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A skill offered by a skill source.
 */
export type SourceSkill = { name: string, description: string, 
/**
 * Relative path from the source root to the skill directory.
 */
path: string, 
/**
 * Whether this skill is already installed in the target scope.
 */
installed: boolean, 
/**
 * Whether the installed copy differs from the source copy.
 */
update_available: boolean, };
