// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelUsage } from "./ModelUsage";
import type { UsageBucket } from "./UsageBucket";

export type UsageResult = { buckets: Array<UsageBucket>, models: Array<ModelUsage>, total: number, sessions: number, };
