// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageBucket = { 
/**
 * Period label: `YYYY-MM-DD` (day), `YYYY-Www` (week), or `YYYY-MM` (month).
 */
period: string, input: number, output: number, cache_read: number, cache_creation: number, total: number, };
